[package]
name = "core"
version = "0.0.1"
authors = []

[lib]
name = "core"
path = "lib.rs"

[dependencies]
net = {path = "../net"}
channel = {path = "../channel"}
channel_traits = {path = "../channel_traits"}
